project:
  type: website

website:
  description: "A blog about learning Python, problem-solving, and transitioning to software engineering"
  site-url: https://jacobmorrin.github.io/blog/
  title: "Jacob Morrin"
  navbar:

    right:
      - text: "posts"
        href: https://jacobmorrin.github.io/blog/
      - text: "about"
        href: about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/jacobmorrin/
      - icon: github
        href: https://github.com/jacobmorrin
      - icon: Linkedin
        href: https://twitter.com
format:
  html:
    include-after-body: counter.html
    theme:
      - yeti
      - brand
    css: styles.css
