project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://github.com/jacobmorrin/blog
  title: "blog"
  navbar:
    left:
        - file: index.qmd
        - file: posts/index.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jacobmorrin
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css



